### ISSUE TITLE
为什么我调用 nat-camrea 不能使用啊 还需要写java文件吗

### ISSUE THREAD

**Issue by to0simple** [Natjs/weex-nat-camera#11]

**Comment by acathur** [comment]
请提供具体信息 @love-YY

**Comment by to0simple** [comment]
E/SafeRunnable: SafeRunnable run throw expection:java.lang.reflect.InvocationTargetException
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.weex.app, PID: 2786
                  java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                      at com.taobao.weex.bridge.NativeInvokeHelper$1.run(NativeInvokeHelper.java:50)
                      at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:49)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                   Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.taobao.weex.bridge.MethodInvoker.invoke(MethodInvoker.java:46)
                      at com.taobao.weex.bridge.NativeInvokeHelper$1.run(NativeInvokeHelper.java:48)
                      at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:49) 
                      at android.os.Handler.handleCallback(Handler.java:751) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
                   Caused by: android.os.FileUriExposedException: file:///storage/emulated/0/Instapp/nat_img_1523237703698.jpg exposed beyond app through ClipData.Item.getUri()
                      at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                      at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                      at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
                      at android.content.Intent.prepareToLeaveProcess(Intent.java:8909)
                      at android.content.Intent.prepareToLeaveProcess(Intent.java:8894)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1517)
                      at android.app.Activity.startActivityForResult(Activity.java:4224)
                      at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                      at android.app.Activity.startActivityForResult(Activity.java:4183)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
                      at com.instapp.nat.camera.CameraModule.captureImage(CameraModule.java:69)
                      at com.instapp.nat.weex.plugin.Camera.Camera.realCaptureImage(Camera.java:59)
                      at com.instapp.nat.weex.plugin.Camera.Camera.captureImage(Camera.java:53)
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.taobao.weex.bridge.MethodInvoker.invoke(MethodInvoker.java:46) 
                      at com.taobao.weex.bridge.NativeInvokeHelper$1.run(NativeInvokeHelper.java:48) 
                      at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:49) 
                      at android.os.Handler.handleCallback(Handler.java:751) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6077) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
Application terminated.
引入 nat之后在android studio虚拟机跑起来  一点击就报这个错误

**Comment by to0simple** [comment]
提示对应的方法  不存在   打印出来的nat对象下面camera存在的

**Comment by acathur** [comment]
尝试在`AndroidManifest.xml`中添加权限
```xml
<uses-permission android:name="android.permission.CAMERA"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
```

**Comment by to0simple** [comment]
我看了一下  我的AndroidManifest.xml中  已经存在了这些权限

**Comment by acathur** [comment]
提供一下设备、系统版本及weex工具套件版本

**Comment by to0simple** [comment]
weexpack : v1.1.8
 - weex-debugger : v1.0.7
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6

win10系统

**Comment by acathur** [comment]
@love-YY Android设备及版本哟

**Comment by to0simple** [comment]
我用的是android studio 虚拟机 版本为6.3

**Comment by to0simple** [comment]
安卓版本 为7.0

**Comment by androidzhangyanhui** [comment]
我也是这个问题，请问你解决了吗？

**Comment by OptimisticZombie** [comment]
ClipData.Item.getUri() 这个因为 targetVersion > 24 了，要么使用 FileProvider 要么降版本，或者直接忽略file:uri错误。
