### ISSUE TITLE
插件安装失败

### ISSUE THREAD

**Issue by daviscai** [Natjs/weex-nat-camera#6]
工程用的是  ElemeFE/weex-vue-starter-kit ，weex-vue-starter-kit下执行 weexpack run android 是可以成功的，但安装插件失败，提示： Could not find gradle wrapper within Android SDK. 具体怎么解决？

```
$ weexpack plugin add nat-camera
Fetching plugin "nat-camera" via npm
Installing "nat-camera@0.1.6" for android
Android Studio project detected
ANDROID_HOME=C:\Users\davis\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_131
Failed to install 'nat-camera':Error
    at Object.module.exports.check_gradle (C:\Users\davis\AppData\Roaming\npm\node_modules\weexpack\lib\src\platforms\android_pack\lib\check_reqs.js:90:25)
    at GradleBuilder.prepEnv (C:\Users\davis\AppData\Roaming\npm\node_modules\weexpack\lib\src\platforms\android_pack\lib\builders\GradleBuilder.js:175:23)
    at Api.module.exports.runClean (C:\Users\davis\AppData\Roaming\npm\node_modules\weexpack\lib\src\platforms\android_pack\lib\build.js:133:20)
    at C:\Users\davis\AppData\Roaming\npm\node_modules\weexpack\lib\src\platforms\android_pack\Api.js:395:50
    at _fulfilled (C:\Users\davis\AppData\Roaming\npm\node_modules\weexpack\node_modules\.1.0.1@q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\davis\AppData\Roaming\npm\node_modules\weexpack\node_modules\.1.0.1@q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\davis\AppData\Roaming\npm\node_modules\weexpack\node_modules\.1.0.1@q\q.js:749:13)
    at C:\Users\davis\AppData\Roaming\npm\node_modules\weexpack\node_modules\.1.0.1@q\q.js:557:44
    at flush (C:\Users\davis\AppData\Roaming\npm\node_modules\weexpack\node_modules\.1.0.1@q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
Error: Could not find gradle wrapper within Android SDK. Might need to update your Android SDK.
Looked here: C:\Users\davis\AppData\Local\Android\sdk\tools\templates\gradle\wrapper

```

**Comment by daviscai** [comment]
解决了，

下载 https://dl.google.com/android/repository/tools_r25.2.3-windows.zip ,解压后，把 templates 文件夹复制到 C:\Users\xxx\AppData\Local\Android\sdk\tools\ ， 这个目录就是上面提示错误信息里最后一句 Looked here: 的目录

重新执行安装就可以了
